### ISSUE TITLE
Mouse position wrong when hovering over plugin.

### ISSUE THREAD

**Issue by ok-nick** [Kampfkarren/hoarcekat#20]
I sent a pr which helps in many ways, including being able to have the correct mouse position, https://github.com/Kampfkarren/hoarcekat/pull/19 (by being on-screen). But technically, since you are already setting the environment of each module, you should easily be able to create a mock UserInputService with GetMouseLocation and all the other mouse features, returning the plugin mouse. The problem with the current mouse is that when it goes onto a plugin gui, it just stops updating and acts as if it hasn't moved.

**Comment by matthargett** [comment]
that PR was merged, should this issue be closed now?
