### ISSUE TITLE
Interact with mouse position

### ISSUE THREAD

**Issue by ZayerRBLX** [Kampfkarren/hoarcekat#28]
How could we interact with the player mouse position?

**Comment by Kampfkarren** [comment]
UserInputService:GetMouseLocation() + full screen mode works I think?

**Comment by ZayerRBLX** [comment]
Indeed, however we cannot use it directly on the plugin, we have to project the view. 
https://gyazo.com/a7484ee49576374a3535134dee69f198

**Comment by Kampfkarren** [comment]
That's not really possible for us to work around, it's going to be inside another UI in the plugin, always. We don't want people to write Hoarcekat specific code. 

Full screen mode is the only reasonable way we can handle this.
